### ISSUE TITLE
Allow excluding links from nav section in header

### ISSUE THREAD

**Issue by weskoerber** [huhu/juice#12]
Currently, all pages create a link in the nav section in the header. I think it would be useful to allow the user to specify pages they do not wish to add to the nav section in the header.

**Comment by weskoerber** [comment]
While I was working on #13 I discovered that the page isn't included in the nav section if I omitted the `weight` key in the page metadata. 

Is there some other way of excluding items from the nav header I'm not aware of?

**Comment by Folyd** [comment]
> While I was working on #13 I discovered that the page isn't included in the nav section if I omitted the `weight` key in the page metadata.
> 
> Is there some other way of excluding items from the nav header I'm not aware of?

Yes, this is the default behavior of zola, see https://www.getzola.org/documentation/content/page/

```toml
# The weight as defined on the Section page of the documentation.
# If the section variable `sort_by` is set to `weight`, then any page that lacks a `weight`
# will not be rendered.
weight = 0
```

**Comment by weskoerber** [comment]
> > While I was working on #13 I discovered that the page isn't included in the nav section if I omitted the `weight` key in the page metadata.
> > Is there some other way of excluding items from the nav header I'm not aware of?
> 
> Yes, this is the default behavior of zola, see https://www.getzola.org/documentation/content/page/
> 
> ```toml
> # The weight as defined on the Section page of the documentation.
> # If the section variable `sort_by` is set to `weight`, then any page that lacks a `weight`
> # will not be rendered.
> weight = 0
> ```

Ah, I missed that in the docs. I guess there's still value in this if the `sort_by` variable is not set to `weight` and the user wishes to exclude the link from the header...
