### ISSUE TITLE
Table of content highlight don't work properly when you scroll

### ISSUE THREAD

**Issue by kevlarcade** [huhu/juice#7]
Table of content highlight don't highlight the few last content you scroll to the bottom of the website, highlight match the first item visible on the screen.

It is visible when you scroll down on your home website, ```Contributing``` will never be highlighted.
![Screenshot 2022-03-30 at 16-18-26 Juice - An intuitive elegant and lightweight Zola theme for product sites](https://user-images.githubusercontent.com/5849253/160856863-d57386dd-7673-4dbe-8c70-affeaec1b2cf.png)

**Comment by Folyd** [comment]
Hi, @kevlarcade. Thanks for the feedback. This has been fixed via https://github.com/huhu/juice/commit/c2ba14f473dccaa040af5034b9d76543b57e69df. 

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/3369694/199889036-3fba125e-9365-4188-b809-858131bda976.png">
