### ISSUE TITLE
Invalid weight setting

### ISSUE THREAD

**Issue by C-BJ** [huhu/juice#8]

**Comment by Folyd** [comment]
Excuse me?

**Comment by C-BJ** [comment]
The markdown files in the contant folder cannot be sorted on the web page by weight 
The order of the options is different each time the build
@Folyd

**Comment by C-BJ** [comment]
https://github.com/erg-lang/erg-lang.org

**Comment by zmitchell** [comment]
I actually see this as well. I think what the original poster meant is that the `weight` field is ignored when rendering the nav e.g. the order of the links is random each time.
